name: C++ CI (Windows)

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: '3.23' # Specify the CMake version here

    - name: Install Vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        vcpkg integrate install
        
    - name: Add MSVC to PATH
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=D:/a/FacebowFileReader/FacebowFileReader/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build build

    - name: Test
      run: cd build && ctest --output-on-failure